// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as $$String from "../node_modules/bs-platform/lib/es6/string.js";

function make(e) {
  return /* :: */[
          e,
          /* [] */0
        ];
}

var concat = List.append;

function show(e) {
  return $$String.concat(" or ", e);
}

export {
  make ,
  concat ,
  show ,
  
}
/* No side effect */
