// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Tea_app from "../node_modules/bucklescript-tea/src-ocaml/tea_app.js";
import * as Tea_html from "../node_modules/bucklescript-tea/src-ocaml/tea_html.js";
import * as La$BlaBla from "./La.bs.js";
import * as Prsr$BlaBla from "./Prsr.bs.js";
import * as Strm$BlaBla from "./Strm.bs.js";

console.log(Strm$BlaBla.to_log(Prsr$BlaBla.parse(La$BlaBla.Parser[/* show */26], Prsr$BlaBla.parse(La$BlaBla.Parser[/* parser */25], Prsr$BlaBla.parse(La$BlaBla.Parser[/* tokens */14], Strm$BlaBla.from_string("\\x y z.x y \\z"))))));

var init = /* record */[/* hello */"world"];

function update(model, msg) {
  return /* record */[/* hello */model[/* hello */0] + "?"];
}

function view(model) {
  return /* Node */Block.__(2, [
            "",
            "h1",
            "",
            "",
            /* :: */[
              /* Event */Block.__(3, [
                  "click",
                  /* EventHandlerMsg */Block.__(1, [/* Nothing */0]),
                  /* record */[/* contents */undefined]
                ]),
              /* [] */0
            ],
            /* :: */[
              /* Text */Block.__(1, ["HELLO, "]),
              /* :: */[
                Tea_html.text(model[/* hello */0]),
                /* :: */[
                  /* Text */Block.__(1, ["."]),
                  /* [] */0
                ]
              ]
            ]
          ]);
}

var partial_arg = /* record */[
  /* model */init,
  /* update */update,
  /* view */view
];

function main(param, param$1) {
  return Tea_app.beginnerProgram(partial_arg, param, param$1);
}

export {
  init ,
  update ,
  view ,
  main ,
  
}
/*  Not a pure module */
